---
abstract: 'Expiremental SMTP server using AnyEvent!'
author:
  - KnowZero
build_requires:
  AnyEvent: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SMTP-Server-AnyEvent
provides:
  Net::SMTP::Server::AnyEvent:
    file: lib/Net/SMTP/Server/AnyEvent.pm
    version: 0.02
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.02
